### ISSUE TITLE
How can i get as86 and ld86 0.16.17 for MacOS?

### ISSUE THREAD

**Issue by dbbbit** [freewilll/linux-evocation#1]

**Comment by freewilll** [comment]
The bin86 package doesn't fully compile successfully when running make, but the as86 and ld86 binaries can be compiled individually using either clang or gcc This was tested on macOS sierra.

Download http://ftp.linuxfoundation.org/pub/lsb/impl/packages/bin86-0.16.17.tar.gz

```
tar xfvz bin86-0.16.17.tar.gz
cd bin86-0.16.17
cd ld
make ld86
cd ..
cd as86
make as86
cd ..
sudo cp ld/ld86 as/as86 /your/preferred/bin/directory
```
